import {
  HazardReport,
  HazardType,
  PredictiveAlert,
  RoadSegment,
  VehicleAccessibilityMatrix,
  VehicleInfo,
  VehicleType,
} from './types';

export const VEHICLE_CATALOG: VehicleInfo[] = [
  {
    type: 'motorcycle',
    label: 'Motorcycle / Two-Wheeler',
    shortLabel: 'Motorcycle',
    category: 'Light Mobility',
    iconName: 'Bike',
    weightTonnes: 0.2,
    groundClearanceMm: 160,
    description: 'High maneuverability; can squeeze through narrow road shoulders (0.8m) if dry.',
  },
  {
    type: 'car',
    label: '4x4 / Passenger Car / SUV',
    shortLabel: '4x4 / Car',
    category: 'Personal Vehicle',
    iconName: 'Car',
    weightTonnes: 1.8,
    groundClearanceMm: 210,
    description: '4WD capability handles moderate debris, loose gravel, and shallow water up to 250mm.',
  },
  {
    type: 'lcv',
    label: 'Small Commercial (LCV / Pickup)',
    shortLabel: 'LCV / Pickup',
    category: 'Light Freight',
    iconName: 'Truck',
    weightTonnes: 3.5,
    groundClearanceMm: 220,
    description: 'Essential for intra-hill vegetable, dairy, and consumer goods distribution.',
  },
  {
    type: 'bus',
    label: 'Passenger Bus (State / Private)',
    shortLabel: 'Bus',
    category: 'Public Transport',
    iconName: 'Bus',
    weightTonnes: 12.0,
    groundClearanceMm: 240,
    description: 'High center of gravity; strict turn radius and weight restrictions on mountain bridges.',
  },
  {
    type: 'heavy_truck',
    label: 'Heavy Multi-Axle Truck (10-12 Wheeler)',
    shortLabel: 'Heavy Truck (25T)',
    category: 'Heavy Freight',
    iconName: 'Container',
    weightTonnes: 25.0,
    groundClearanceMm: 280,
    description: 'Carries industrial freight, construction materials, steel; vulnerable to sinkholes and mud traps.',
  },
  {
    type: 'loaded_truck',
    label: 'Loaded Freight Rig / 16-Wheeler',
    shortLabel: 'Loaded Rig (42T)',
    category: 'Bulk Logistics',
    iconName: 'Boxes',
    weightTonnes: 42.0,
    groundClearanceMm: 260,
    description: 'Maximum weight class; completely impassable on compromised bridges or soft road edges.',
  },
  {
    type: 'emergency',
    label: 'Emergency / NDRF / 4WD Ambulance',
    shortLabel: 'NDRF / Emergency',
    category: 'Priority Relief',
    iconName: 'ShieldAlert',
    weightTonnes: 4.5,
    groundClearanceMm: 300,
    description: 'Equipped with winches, high snorkels, and priority clearance escort protocols.',
  },
];

export const INITIAL_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-nh6-sonapur',
    name: 'NH-6: Jowai to Sonapur Tunnel & Lubha Bridge',
    highwayCode: 'NH-6',
    state: 'Meghalaya',
    startCity: 'Jowai',
    endCity: 'Sonapur',
    startCoords: [25.452, 92.203],
    endCoords: [25.109, 92.368],
    polyline: [
      [25.452, 92.203],
      [25.385, 92.251],
      [25.312, 92.298],
      [25.241, 92.335],
      [25.182, 92.352],
      [25.109, 92.368],
    ],
    elevationMeters: 1380,
    lengthKm: 58,
    currentStatus: 'critical',
    currentHazard: 'landslide',
    obstructionPercentage: 92,
    lastReportTime: '12 mins ago',
    reportCount: 14,
    verified: true,
    officialNotes: 'Major rockfall & mudflow near Sonapur tunnel portal. BRO 765 BRTF heavy earthmovers deployed.',
    weatherWarning: 'Torrential 74mm/hr rainfall in East Jaintia Hills',
    alternateSegmentId: 'seg-nh6-alternate-dudhnoi',
    alternateRouteDescription: 'Via Guwahati - Dudhnoi - Tura - Dalu southern corridor (adds 4.5 hrs, but 100% stable).',
    historicalIncidentRate: 88,
    liveSensorData: {
      rainfallMmH: 74,
      soilMoisturePct: 96,
      slopeInstability: 'Critical',
      ambientTempC: 18,
    },
    vehicleAccess: {
      motorcycle: {
        status: 'caution',
        canPass: true,
        advice: 'Passable with manual escort over 1m stabilized shoulder edge.',
        delayMin: 25,
      },
      car: {
        status: 'blocked',
        canPass: false,
        advice: 'Debris boulders > 400mm exceed SUV ground clearance. Turn back at Khliehriat.',
        delayMin: 240,
      },
      lcv: {
        status: 'blocked',
        canPass: false,
        advice: 'Mud slurry depth 500mm causes axle wheel-spin. Reroute advised.',
        delayMin: 240,
      },
      bus: {
        status: 'blocked',
        canPass: false,
        advice: 'Road width reduced to 1.8m. Unsafe for wide body coaches.',
        delayMin: 360,
      },
      heavy_truck: {
        status: 'blocked',
        canPass: false,
        advice: 'Complete blockage for heavy vehicles. Sinking edge cannot sustain > 10 tonnes.',
        delayMin: 480,
      },
      loaded_truck: {
        status: 'blocked',
        canPass: false,
        advice: 'Strictly prohibited. Structural bridge abutment check underway.',
        delayMin: 600,
      },
      emergency: {
        status: 'caution',
        canPass: true,
        advice: 'Winch-assisted passage cleared on single lane under BRO pilot escort.',
        delayMin: 20,
      },
    },
  },
  {
    id: 'seg-nh6-jorabat-shillong',
    name: 'NH-6: Guwahati (Jorabat) to Shillong 4-Lane Expressway',
    highwayCode: 'NH-6',
    state: 'Meghalaya',
    startCity: 'Guwahati',
    endCity: 'Shillong',
    startCoords: [26.115, 91.874],
    endCoords: [25.578, 91.893],
    polyline: [
      [26.115, 91.874],
      [25.986, 91.884],
      [25.864, 91.886],
      [25.753, 91.892],
      [25.665, 91.905],
      [25.578, 91.893],
    ],
    elevationMeters: 1496,
    lengthKm: 98,
    currentStatus: 'minor',
    currentHazard: 'mudslide',
    obstructionPercentage: 25,
    lastReportTime: '28 mins ago',
    reportCount: 3,
    verified: true,
    officialNotes: 'Minor shoulder mud sliding near Umiam lake viewpoint. 1 lane active in each direction.',
    weatherWarning: 'Dense mountain fog reducing visibility < 30m',
    historicalIncidentRate: 34,
    liveSensorData: {
      rainfallMmH: 22,
      soilMoisturePct: 68,
      slopeInstability: 'Moderate',
      ambientTempC: 16,
    },
    vehicleAccess: {
      motorcycle: { status: 'passable', canPass: true, advice: 'Clear lane available. Watch for slick road paint.', delayMin: 5 },
      car: { status: 'passable', canPass: true, advice: 'Clear lane available. Maintain 40 km/h speed limit.', delayMin: 10 },
      lcv: { status: 'passable', canPass: true, advice: 'Passable with minor traffic slowing.', delayMin: 15 },
      bus: { status: 'passable', canPass: true, advice: 'Passable with caution on hairpin turns.', delayMin: 20 },
      heavy_truck: { status: 'caution', canPass: true, advice: 'Single lane operation; expect queue at Umiam bridge.', delayMin: 35 },
      loaded_truck: { status: 'caution', canPass: true, advice: 'Reduce speed on descents; brake heating warning.', delayMin: 45 },
      emergency: { status: 'passable', canPass: true, advice: 'Priority green corridor open on outer lane.', delayMin: 0 },
    },
  },
  {
    id: 'seg-nh27-kaziranga',
    name: 'NH-27: Nagaon to Kaziranga (Brahmaputra Flood Corridor)',
    highwayCode: 'NH-27',
    state: 'Assam',
    startCity: 'Nagaon',
    endCity: 'Kaziranga',
    startCoords: [26.345, 92.684],
    endCoords: [26.577, 93.171],
    polyline: [
      [26.345, 92.684],
      [26.412, 92.834],
      [26.498, 93.012],
      [26.544, 93.105],
      [26.577, 93.171],
    ],
    elevationMeters: 74,
    lengthKm: 82,
    currentStatus: 'restricted',
    currentHazard: 'flood',
    obstructionPercentage: 45,
    lastReportTime: '45 mins ago',
    reportCount: 8,
    verified: true,
    officialNotes: 'Flood waters overtopping road at Kohora & Bagori ranges (180mm depth). Speed capped at 40 km/h for wildlife sensor corridor.',
    weatherWarning: 'Brahmaputra river level 0.45m above danger mark at Tezpur',
    historicalIncidentRate: 72,
    liveSensorData: {
      rainfallMmH: 38,
      soilMoisturePct: 98,
      slopeInstability: 'Stable',
      ambientTempC: 27,
    },
    vehicleAccess: {
      motorcycle: { status: 'caution', canPass: true, advice: 'Water logging 150mm. Stalling risk on small silencers.', delayMin: 30 },
      car: { status: 'passable', canPass: true, advice: 'Proceed in low gear. Adhere strictly to animal corridor sensor zones.', delayMin: 25 },
      lcv: { status: 'passable', canPass: true, advice: 'High intake clearance permits safe crossing.', delayMin: 15 },
      bus: { status: 'passable', canPass: true, advice: 'Speed restricted to 40 km/h; forest department convoy.', delayMin: 20 },
      heavy_truck: { status: 'passable', canPass: true, advice: 'Safe passage; maintain 50m vehicle spacing.', delayMin: 15 },
      loaded_truck: { status: 'passable', canPass: true, advice: 'Safe passage; avoid overtaking on submerged shoulders.', delayMin: 20 },
      emergency: { status: 'passable', canPass: true, advice: 'Clear priority corridor enabled.', delayMin: 0 },
    },
  },
  {
    id: 'seg-nh10-teesta',
    name: 'NH-10: Sevoke to Teesta Bazaar & Rangpo (Sikkim Lifeline)',
    highwayCode: 'NH-10',
    state: 'Sikkim',
    startCity: 'Sevoke',
    endCity: 'Rangpo',
    startCoords: [26.883, 88.472],
    endCoords: [27.176, 88.528],
    polyline: [
      [26.883, 88.472],
      [26.962, 88.489],
      [27.045, 88.478],
      [27.112, 88.502],
      [27.176, 88.528],
    ],
    elevationMeters: 850,
    lengthKm: 52,
    currentStatus: 'critical',
    currentHazard: 'road_collapse',
    obstructionPercentage: 85,
    lastReportTime: '18 mins ago',
    reportCount: 11,
    verified: true,
    officialNotes: 'Teesta river embankment erosion caused 40m road collapse at 29th Mile. Light vehicles diverted via Mungpoo.',
    weatherWarning: 'Teesta upstream water discharge spike',
    alternateSegmentId: 'seg-nh10-bypass-mungpoo',
    alternateRouteDescription: 'Via Siliguri - Gorubathan - Lava - Reshi - Pedong - Rorathang (heavy vehicle alternative).',
    historicalIncidentRate: 94,
    liveSensorData: {
      rainfallMmH: 62,
      soilMoisturePct: 94,
      slopeInstability: 'Critical',
      ambientTempC: 20,
    },
    vehicleAccess: {
      motorcycle: { status: 'caution', canPass: true, advice: 'Narrow footpath bypass constructed for two-wheelers only.', delayMin: 30 },
      car: { status: 'blocked', canPass: false, advice: 'Road width insufficient. Diversion mandatory via Mungpoo.', delayMin: 180 },
      lcv: { status: 'blocked', canPass: false, advice: 'Strictly diverted via Lava-Algarah-Pedong.', delayMin: 220 },
      bus: { status: 'blocked', canPass: false, advice: 'All tourist and state transport buses diverted via Reshi.', delayMin: 260 },
      heavy_truck: { status: 'blocked', canPass: false, advice: 'Total ban on heavy vehicles on NH-10. Use Gorubathan route.', delayMin: 360 },
      loaded_truck: { status: 'blocked', canPass: false, advice: 'Total ban on loaded trucks. Axle limit exceeded on temporary fills.', delayMin: 420 },
      emergency: { status: 'emergency_only', canPass: true, advice: 'Helicopter evacuation active; narrow 4x4 pilot only.', delayMin: 40 },
    },
  },
  {
    id: 'seg-nh13-sela',
    name: 'NH-13: Bomdila - Dirang - Sela Pass to Tawang',
    highwayCode: 'NH-13',
    state: 'Arunachal Pradesh',
    startCity: 'Bomdila',
    endCity: 'Tawang',
    startCoords: [27.264, 92.423],
    endCoords: [27.586, 91.868],
    polyline: [
      [27.264, 92.423],
      [27.358, 92.241],
      [27.462, 92.102],
      [27.505, 92.015],
      [27.586, 91.868],
    ],
    elevationMeters: 4170,
    lengthKm: 142,
    currentStatus: 'predicted_high_risk',
    currentHazard: 'rockfall',
    obstructionPercentage: 40,
    lastReportTime: '1 hr ago',
    reportCount: 5,
    verified: true,
    officialNotes: 'Sub-zero temperatures creating black ice near Sela Tunnel approaches; rockfall advisory active on Jaswant Garh stretch.',
    weatherWarning: 'Blizzard alert: Wind gusts 65 km/h, -4°C temperature',
    historicalIncidentRate: 78,
    liveSensorData: {
      rainfallMmH: 14,
      soilMoisturePct: 82,
      slopeInstability: 'High',
      ambientTempC: -2,
    },
    vehicleAccess: {
      motorcycle: { status: 'blocked', canPass: false, advice: 'Extreme black ice danger. Two wheelers restricted by district administration.', delayMin: 180 },
      car: { status: 'caution', canPass: true, advice: '4x4 with snow chains permitted during daylight hours (06:00 - 16:00).', delayMin: 60 },
      lcv: { status: 'caution', canPass: true, advice: 'Chains required on drive wheels. Max speed 25 km/h.', delayMin: 75 },
      bus: { status: 'caution', canPass: true, advice: 'Military & ASTC convoy movement only.', delayMin: 90 },
      heavy_truck: { status: 'caution', canPass: true, advice: 'Army logistics convoy priority. Commercial trucks spaced by 15 mins.', delayMin: 120 },
      loaded_truck: { status: 'blocked', canPass: false, advice: 'Overweight trucks (> 20T) restricted due to icing on 14% gradients.', delayMin: 300 },
      emergency: { status: 'passable', canPass: true, advice: 'Army / Medical 4WD vehicles operational with tire studs.', delayMin: 15 },
    },
  },
  {
    id: 'seg-nh2-kohima-imphal',
    name: 'NH-2: Kohima - Mao - Kangpokpi - Imphal Highway',
    highwayCode: 'NH-2',
    state: 'Nagaland',
    startCity: 'Kohima',
    endCity: 'Imphal',
    startCoords: [25.674, 94.108],
    endCoords: [24.817, 93.936],
    polyline: [
      [25.674, 94.108],
      [25.521, 94.142],
      [25.328, 94.021],
      [25.012, 93.965],
      [24.817, 93.936],
    ],
    elevationMeters: 1440,
    lengthKm: 138,
    currentStatus: 'minor',
    currentHazard: 'road_damage',
    obstructionPercentage: 20,
    lastReportTime: '2 hrs ago',
    reportCount: 4,
    verified: false,
    officialNotes: 'Subsidence patching ongoing near Phesama sinking zone. Traffic regulated by Nagaland Police.',
    historicalIncidentRate: 64,
    liveSensorData: {
      rainfallMmH: 18,
      soilMoisturePct: 71,
      slopeInstability: 'Moderate',
      ambientTempC: 22,
    },
    vehicleAccess: {
      motorcycle: { status: 'passable', canPass: true, advice: 'Passable. Rough patches near Mao gate.', delayMin: 10 },
      car: { status: 'passable', canPass: true, advice: 'Passable. Drive carefully on uneven gravel stretches.', delayMin: 15 },
      lcv: { status: 'passable', canPass: true, advice: 'Passable. Standard travel time.', delayMin: 20 },
      bus: { status: 'passable', canPass: true, advice: 'Regular scheduled bus service active.', delayMin: 25 },
      heavy_truck: { status: 'passable', canPass: true, advice: 'Slow moving over sinking zone; 15 km/h.', delayMin: 40 },
      loaded_truck: { status: 'caution', canPass: true, advice: 'Check tire pressures and load balance before Mao descent.', delayMin: 50 },
      emergency: { status: 'passable', canPass: true, advice: 'All emergency vehicles unimpeded.', delayMin: 0 },
    },
  },
  {
    id: 'seg-nh306-silchar-aizawl',
    name: 'NH-306 / NH-6: Silchar - Kolasib - Sairang - Aizawl',
    highwayCode: 'NH-306',
    state: 'Mizoram',
    startCity: 'Silchar',
    endCity: 'Aizawl',
    startCoords: [24.833, 92.778],
    endCoords: [23.727, 92.717],
    polyline: [
      [24.833, 92.778],
      [24.498, 92.712],
      [24.215, 92.684],
      [23.945, 92.695],
      [23.727, 92.717],
    ],
    elevationMeters: 1132,
    lengthKm: 165,
    currentStatus: 'safe',
    obstructionPercentage: 0,
    lastReportTime: '3 hrs ago',
    reportCount: 1,
    verified: true,
    officialNotes: 'Road surface dry and all Bailey bridges cleared. Normal commercial freight flow.',
    historicalIncidentRate: 45,
    liveSensorData: {
      rainfallMmH: 5,
      soilMoisturePct: 42,
      slopeInstability: 'Stable',
      ambientTempC: 24,
    },
    vehicleAccess: {
      motorcycle: { status: 'passable', canPass: true, advice: 'Clear corridor. Good road surface.', delayMin: 0 },
      car: { status: 'passable', canPass: true, advice: 'Clear corridor. Smooth driving conditions.', delayMin: 0 },
      lcv: { status: 'passable', canPass: true, advice: 'Clear corridor. Essential supplies moving freely.', delayMin: 0 },
      bus: { status: 'passable', canPass: true, advice: 'All scheduled services on time.', delayMin: 0 },
      heavy_truck: { status: 'passable', canPass: true, advice: 'Max 25T axle loading permitted.', delayMin: 10 },
      loaded_truck: { status: 'passable', canPass: true, advice: 'Observe weight placards at Bailey bridges.', delayMin: 15 },
      emergency: { status: 'passable', canPass: true, advice: 'Clear corridor.', delayMin: 0 },
    },
  },
  {
    id: 'seg-nh6-alternate-dudhnoi',
    name: 'NH-17 / NH-217: Guwahati - Goalpara - Dudhnoi - Tura - Dalu Bypass',
    highwayCode: 'NH-17',
    state: 'Assam',
    startCity: 'Guwahati',
    endCity: 'Dalu',
    startCoords: [26.185, 91.736],
    endCoords: [25.215, 90.218],
    polyline: [
      [26.185, 91.736],
      [26.012, 90.985],
      [25.824, 90.652],
      [25.512, 90.221],
      [25.215, 90.218],
    ],
    elevationMeters: 420,
    lengthKm: 218,
    currentStatus: 'safe',
    obstructionPercentage: 0,
    lastReportTime: '15 mins ago',
    reportCount: 2,
    verified: true,
    officialNotes: 'Designated national highway bypass corridor for Silchar & Tripura freight when NH-6 Jowai-Sonapur is blocked.',
    historicalIncidentRate: 15,
    liveSensorData: {
      rainfallMmH: 12,
      soilMoisturePct: 50,
      slopeInstability: 'Stable',
      ambientTempC: 28,
    },
    vehicleAccess: {
      motorcycle: { status: 'passable', canPass: true, advice: 'Wide 2-lane smooth paved road.', delayMin: 0 },
      car: { status: 'passable', canPass: true, advice: 'Excellent highway surface, fast transit.', delayMin: 0 },
      lcv: { status: 'passable', canPass: true, advice: 'Unrestricted transit.', delayMin: 0 },
      bus: { status: 'passable', canPass: true, advice: 'Unrestricted transit.', delayMin: 0 },
      heavy_truck: { status: 'passable', canPass: true, advice: 'Recommended bypass for all multi-axle freight.', delayMin: 0 },
      loaded_truck: { status: 'passable', canPass: true, advice: 'High-capacity culverts and bridges handle 42T rigs.', delayMin: 0 },
      emergency: { status: 'passable', canPass: true, advice: 'All emergency vehicles unrestricted.', delayMin: 0 },
    },
  },
];

export const INITIAL_HAZARD_REPORTS: HazardReport[] = [
  {
    id: 'rep-101',
    timestamp: '12 mins ago',
    segmentId: 'seg-nh6-sonapur',
    segmentName: 'NH-6: Jowai to Sonapur Tunnel',
    highwayCode: 'NH-6',
    state: 'Meghalaya',
    coords: [25.109, 92.368],
    locationDescription: '1.2 km south of Sonapur Tunnel entrance, East Jaintia Hills',
    hazardType: 'landslide',
    description: 'Massive slope failure after cloudburst. Debris, large boulders and tree trunks cover 90% of the two-lane road. Mud depth is over 2 feet.',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=800',
    aiConfidence: 94,
    severity: 'critical',
    obstructionPercentage: 92,
    verified: true,
    verifiedBy: 'BRO Control Room (765 BRTF)',
    reportedBy: 'Freight Driver (Assam-Tripura Logistics)',
    clearingTeamDispatched: true,
    recommendedAction: 'Mandatory diversion of all heavy commercial vehicles via Guwahati-Dudhnoi-Tura. Two-wheelers proceed with extreme caution.',
    boundingBoxes: [
      { label: 'Mudslide Flow', confidence: 96, box: [15, 30, 68, 55] },
      { label: 'Debris Boulder (450mm)', confidence: 92, box: [42, 60, 22, 28] },
      { label: 'Submerged Road Surface', confidence: 94, box: [5, 45, 88, 48] },
    ],
    vehicleAccess: INITIAL_ROAD_SEGMENTS[0].vehicleAccess,
  },
  {
    id: 'rep-102',
    timestamp: '18 mins ago',
    segmentId: 'seg-nh10-teesta',
    segmentName: 'NH-10: Sevoke to Teesta Bazaar',
    highwayCode: 'NH-10',
    state: 'Sikkim',
    coords: [27.045, 88.478],
    locationDescription: '29th Mile, Teesta Riverbank gorge',
    hazardType: 'road_collapse',
    description: 'River scour washed out 40 meters of downhill retaining wall. Edge is shearing off continuously into the river.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800',
    aiConfidence: 92,
    severity: 'critical',
    obstructionPercentage: 85,
    verified: true,
    verifiedBy: 'Sikkim State Disaster Management',
    reportedBy: 'State Transport Bus Pilot',
    clearingTeamDispatched: true,
    recommendedAction: 'Road closed for all commercial 4-wheelers. Reroute via Lava/Gorubathan.',
    boundingBoxes: [
      { label: 'Collapsed Riverbank Toe (40m)', confidence: 95, box: [20, 45, 60, 50] },
      { label: 'Sheared Embankment Void', confidence: 91, box: [45, 35, 35, 25] },
    ],
    vehicleAccess: INITIAL_ROAD_SEGMENTS[3].vehicleAccess,
  },
  {
    id: 'rep-103',
    timestamp: '45 mins ago',
    segmentId: 'seg-nh27-kaziranga',
    segmentName: 'NH-27: Nagaon to Kaziranga',
    highwayCode: 'NH-27',
    state: 'Assam',
    coords: [26.544, 93.105],
    locationDescription: 'Near Bagori Wildlife Range Corridor',
    hazardType: 'flood',
    description: 'Brahmaputra backwaters spilling across 400m highway stretch at 150-180mm depth.',
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&q=80&w=800',
    aiConfidence: 91,
    severity: 'restricted',
    obstructionPercentage: 45,
    verified: true,
    verifiedBy: 'Assam Forest Highway Patrol',
    reportedBy: 'Local Commuter',
    clearingTeamDispatched: false,
    recommendedAction: 'Automated animal sensor speed limit (40 km/h) strictly enforced. Trucks clear to pass.',
    vehicleAccess: INITIAL_ROAD_SEGMENTS[2].vehicleAccess,
  },
  {
    id: 'rep-104',
    timestamp: '1 hr ago',
    segmentId: 'seg-nh13-sela',
    segmentName: 'NH-13: Bomdila to Tawang',
    highwayCode: 'NH-13',
    state: 'Arunachal Pradesh',
    coords: [27.505, 92.015],
    locationDescription: 'Sela Tunnel West Portal Approach, 13,700 ft',
    hazardType: 'rockfall',
    description: 'Freeze-thaw rockfall shattered onto pavement. Boulders cleared from single lane, but black ice persists.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    aiConfidence: 89,
    severity: 'predicted_high_risk',
    obstructionPercentage: 40,
    verified: true,
    verifiedBy: 'Border Roads Organisation (Project Vartak)',
    reportedBy: 'Army Supply Convoy',
    clearingTeamDispatched: true,
    recommendedAction: 'Snow chains mandatory for all civilian 4x4s. Heavy freight paused till daytime salt spreading.',
    vehicleAccess: INITIAL_ROAD_SEGMENTS[4].vehicleAccess,
  },
];

export const INITIAL_PREDICTIVE_ALERTS: PredictiveAlert[] = [
  {
    id: 'pred-201',
    timestamp: '5 mins ago',
    state: 'Meghalaya',
    corridor: 'NH-6 (Jowai - Sonapur - Ratacherra)',
    segmentId: 'seg-nh6-sonapur',
    coords: [25.109, 92.368],
    hazardType: 'landslide',
    severity: 'critical',
    probabilityPct: 94,
    timeframe: 'Active now & Next 6 hours',
    triggerReason: 'IMD cloudburst (74mm/hr) + 96% soil moisture saturation in steep sandstone slope',
    recommendedAction: 'All commercial freight bound for Silchar, Tripura, and Mizoram must divert via Western Meghalaya Bypass.',
    affectedVehicles: ['car', 'lcv', 'bus', 'heavy_truck', 'loaded_truck'],
  },
  {
    id: 'pred-202',
    timestamp: '25 mins ago',
    state: 'Sikkim',
    corridor: 'NH-10 (Sevoke - Teesta Bazaar)',
    segmentId: 'seg-nh10-teesta',
    coords: [27.045, 88.478],
    hazardType: 'road_collapse',
    severity: 'critical',
    probabilityPct: 91,
    timeframe: 'Next 12-24 hours',
    triggerReason: 'Teesta Hydro Dam discharge surge scouring vulnerable NH-10 road toe',
    recommendedAction: 'Full ban on commercial 10-wheeler trucks. Use Gorubathan-Lava corridor.',
    affectedVehicles: ['car', 'bus', 'lcv', 'heavy_truck', 'loaded_truck'],
  },
  {
    id: 'pred-203',
    timestamp: '40 mins ago',
    state: 'Arunachal Pradesh',
    corridor: 'NH-13 (Bhalukpong - Tawang)',
    segmentId: 'seg-nh13-sela',
    coords: [27.505, 92.015],
    hazardType: 'rockfall',
    severity: 'predicted_high_risk',
    probabilityPct: 86,
    timeframe: '18:00 to 06:00 (Night window)',
    triggerReason: 'Sub-zero thermal contraction fracturing fissured granite cliffs near Jaswant Garh',
    recommendedAction: 'Two-wheelers prohibited. High-clearance 4WD vehicles only with anti-skid chains.',
    affectedVehicles: ['motorcycle', 'loaded_truck'],
  },
  {
    id: 'pred-204',
    timestamp: '1 hr ago',
    state: 'Assam',
    corridor: 'NH-27 (Kaziranga - Bokakhat)',
    segmentId: 'seg-nh27-kaziranga',
    coords: [26.544, 93.105],
    hazardType: 'flood',
    severity: 'restricted',
    probabilityPct: 78,
    timeframe: 'Next 4-8 hours',
    triggerReason: 'Diphlu & Brahmaputra river backflow overflowing low-lying highway culverts',
    recommendedAction: 'Night convoy escort with pilot vehicles. Slow down for crossing wildlife.',
    affectedVehicles: ['motorcycle'],
  },
  {
    id: 'pred-205',
    timestamp: '2 hrs ago',
    state: 'Nagaland',
    corridor: 'NH-2 (Kohima - Phesama Sinking Zone)',
    segmentId: 'seg-nh2-kohima-imphal',
    coords: [25.674, 94.108],
    hazardType: 'mudslide',
    severity: 'minor',
    probabilityPct: 65,
    timeframe: 'Next 12 hours',
    triggerReason: 'Continuous drizzle lubricating clay substrata under NH-2 pavement',
    recommendedAction: 'Maintain steady speed, avoid harsh braking on freshly graded gravel stretches.',
    affectedVehicles: ['loaded_truck'],
  },
];

export const SAMPLE_HAZARD_PRESETS = [
  {
    id: 'preset-landslide-sonapur',
    name: 'Sonapur Massive Landslide (NH-6 Meghalaya)',
    hazardType: 'landslide' as HazardType,
    highwayCode: 'NH-6',
    segmentId: 'seg-nh6-sonapur',
    state: 'Meghalaya',
    coords: [25.109, 92.368] as [number, number],
    locationDescription: 'Sonapur Tunnel Portal, NH-6',
    description: 'Steep hill collapse covering 90% road width with mud and boulders. Over 2 ft silt.',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=800',
    confidence: 95,
    severity: 'critical' as const,
    obstructionPct: 92,
  },
  {
    id: 'preset-flood-kaziranga',
    name: 'Kaziranga River Inundation (NH-27 Assam)',
    hazardType: 'flood' as HazardType,
    highwayCode: 'NH-27',
    segmentId: 'seg-nh27-kaziranga',
    state: 'Assam',
    coords: [26.544, 93.105] as [number, number],
    locationDescription: 'Bagori Range Corridor, NH-27',
    description: 'Brahmaputra tributary water overflow across 300m highway stretch at 180mm depth.',
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&q=80&w=800',
    confidence: 92,
    severity: 'restricted' as const,
    obstructionPct: 45,
  },
  {
    id: 'preset-rockfall-sela',
    name: 'Sela Pass Black Ice & Boulder Fall (NH-13 Arunachal)',
    hazardType: 'rockfall' as HazardType,
    highwayCode: 'NH-13',
    segmentId: 'seg-nh13-sela',
    state: 'Arunachal Pradesh',
    coords: [27.505, 92.015] as [number, number],
    locationDescription: 'Sela Tunnel West Portal, 13,700 ft',
    description: 'Granite boulders shattered across outer lane; black ice slick on 12% incline.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    confidence: 89,
    severity: 'predicted_high_risk' as const,
    obstructionPct: 40,
  },
  {
    id: 'preset-tree-dima',
    name: 'Dima Hasao Fallen Pine Trees (NH-27 / NH-54 Assam)',
    hazardType: 'fallen_tree' as HazardType,
    highwayCode: 'NH-27',
    segmentId: 'seg-nh6-jorabat-shillong',
    state: 'Assam',
    coords: [25.753, 91.892] as [number, number],
    locationDescription: 'Nongpoh Ghat stretch, NH-6',
    description: 'Uprooted 40ft pine tree blocking right lane following squall winds.',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&q=80&w=800',
    confidence: 97,
    severity: 'minor' as const,
    obstructionPct: 35,
  },
];

export const HUB_CITIES = [
  { id: 'guwahati', name: 'Guwahati', state: 'Assam', coords: [26.144, 91.736] as [number, number], hubType: 'Primary Logistics Gateway' },
  { id: 'shillong', name: 'Shillong', state: 'Meghalaya', coords: [25.578, 91.893] as [number, number], hubType: 'Hill State Capital' },
  { id: 'silchar', name: 'Silchar', state: 'Assam', coords: [24.833, 92.778] as [number, number], hubType: 'Barak Valley Hub' },
  { id: 'gangtok', name: 'Gangtok', state: 'Sikkim', coords: [27.338, 88.606] as [number, number], hubType: 'High Altitude Hub' },
  { id: 'tawang', name: 'Tawang', state: 'Arunachal Pradesh', coords: [27.586, 91.868] as [number, number], hubType: 'Strategic Border Outpost' },
  { id: 'imphal', name: 'Imphal', state: 'Manipur', coords: [24.817, 93.936] as [number, number], hubType: 'Cross-Border Corridor' },
  { id: 'kohima', name: 'Kohima', state: 'Nagaland', coords: [25.674, 94.108] as [number, number], hubType: 'Mountain Transit Center' },
  { id: 'aizawl', name: 'Aizawl', state: 'Mizoram', coords: [23.727, 92.717] as [number, number], hubType: 'Southern Terminal' },
  { id: 'agartala', name: 'Agartala', state: 'Tripura', coords: [23.831, 91.286] as [number, number], hubType: 'Border Trade Port' },
  { id: 'itanagar', name: 'Itanagar', state: 'Arunachal Pradesh', coords: [27.084, 93.605] as [number, number], hubType: 'Foothill Capital' },
  { id: 'siliguri', name: 'Siliguri (Chicken Neck)', state: 'West Bengal', coords: [26.727, 88.395] as [number, number], hubType: 'NE Corridor Gateway' },
];
